### PR TITLE
Encryption

### LINKED ISSUE #229: Implement encrypted communication with pattoo_api_agentd
pattoo-shared and pattoo-agents will need to be adjusted to support this.

### LINKED ISSUE #294: Public/Private Key Management
- Generate keys.
- Make sure the keys aren't stored GitHub. 
- Putting the public/private key certificates in a well known location. Have it on the agent and api repo. 
- Avoid overwriting certificates.

### PR DESCRIPTION
**Pull request by gill876**
close #294 
close #229
Encrypted communication support with the agent.
Add simple instructions for local `pattoo_unittest` mysql database set up

### CODE REVIEW

**Comment by palisadoes** [comment]
[You have conflicts to resolve in the pip_requirements.txt file prior to approving this.](https://github.com/PalisadoesFoundation/pattoo/pull/335)

**Comment by gill876** [comment]
> [You have conflicts to resolve in the pip_requirements.txt file prior to approving this.](https://github.com/PalisadoesFoundation/pattoo/pull/335)

I updated it to PattooShared==0.0.89

**Comment by palisadoes** [comment]
> > [You have conflicts to resolve in the pip_requirements.txt file prior to approving this.](https://github.com/PalisadoesFoundation/pattoo/pull/335)
> 
> I updated it to PattooShared==0.0.89

Errors have caused it to fail. You will need to update to 90, unless Jason gets there first. [Check the latest versions here](https://pypi.org/project/PattooShared/#history).

**Comment by palisadoes** [comment]
Still failing. Please resolve.

**Pull request merged**
